"""Evidence verification for extracted field quotes.

Verifies that evidence quotes provided by AI models actually exist in the source transcript
or poster text, flagging model hallucinations.
"""
import re
from typing import Optional, Tuple


def _normalize(text: str) -> str:
    """Normalizes text for fuzzy/substring matching by stripping punctuation and lowercasing."""
    if not text:
        return ""
    # Lowercase and replace non-alphanumeric characters with spaces
    cleaned = re.sub(r"[^\w\s]", " ", text.lower())
    # Collapse multiple spaces
    return re.sub(r"\s+", " ", cleaned).strip()


def verify_evidence(quote: Optional[str], source_text: Optional[str]) -> bool:
    """Returns True if evidence quote is non-empty and found in source_text.
    
    Catches hallucinated quotes generated by LLMs.
    """
    if not quote or not quote.strip():
        return False
    if not source_text or not source_text.strip():
        return False

    norm_quote = _normalize(quote)
    norm_source = _normalize(source_text)

    if not norm_quote:
        return False

    # 1. Exact normalized substring match
    if norm_quote in norm_source:
        return True

    # 2. Token overlap check (for slight transcription variations)
    quote_tokens = norm_quote.split()
    source_tokens = set(norm_source.split())

    if not quote_tokens:
        return False

    matches = sum(1 for token in quote_tokens if token in source_tokens)
    ratio = matches / len(quote_tokens)

    # Require at least 80% token match for multi-word quotes
    return ratio >= 0.8
